spring.application.name=backend
spring.mustache.suffix=.html
logging.level.org.springframework.web=DEBUG

# ── HTTPS / SSL ──────────────────────────────────────────────────────────────
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=123456
server.ssl.key-alias=ecomostoles

# ── H2 Database Console ──────────────────────────────────────────────────────
# Configuración fija para la base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Esto es CRÍTICO para que funcione dentro de los frames de la consola con Spring Security
server.servlet.context-path=
spring.queries.hibernate.default_schema=