package es.urjc.ecomostoles.backend.component;

import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Value;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import es.urjc.ecomostoles.backend.service.ConfigurationService;
import es.urjc.ecomostoles.backend.repository.ImpactFactorRepository;
import es.urjc.ecomostoles.backend.model.ImpactFactor;

/**
 * Component responsible for encapsulating environmental impact logic.
 * 
 * Centralizes sustainability metrics computation, fetching environmental factors
 * dynamically from the database. This avoids business logic leakage across services
 * and adheres to the DRY principle.
 */
@Component
public class SustainabilityEngine {

    private static final Logger log = LoggerFactory.getLogger(SustainabilityEngine.class);

    @Value("${app.sustainability.default-co2-factor:0.45}")
    private double defaultCo2Factor;

    private final ConfigurationService configurationService;
    private final ImpactFactorRepository impactFactorRepository;

    public SustainabilityEngine(ConfigurationService configurationService,
            ImpactFactorRepository impactFactorRepository) {
        this.configurationService = configurationService;
        this.impactFactorRepository = impactFactorRepository;
    }

    /**
     * Calculates the estimated CO2 savings generated by a material transaction.
     * 
     * @param materialAmount the total amount of material (typically in kg).
     * @param wasteCategory the specific category of the material to apply localized metrics.
     * @return the calculated CO2 impact in metric tons.
     */
    public double calculateCo2Impact(double materialAmount, String wasteCategory) {
        String factorStr = configurationService.getConfigurationValue("CO2_FACTOR",
                String.valueOf(defaultCo2Factor));
        double factor;
        try {
            factor = Double.parseDouble(factorStr);
        } catch (NumberFormatException | NullPointerException e) {
            log.warn(
                    "⚠️ CRITICAL CONFIGURATION ERROR: The 'CO2_FACTOR' factor in DB ('{}') is not a valid number. Using safety injected value: {}. Failure: {}",
                    factorStr, defaultCo2Factor, e.getMessage());
            factor = defaultCo2Factor;
        }

        // Retrieve the granular factor from the environmental repository.
        // This ensures calculations adjust dynamically if platform policies or real-world metrics change.
        double materialMultiplier = 1.0;
        if (wasteCategory != null && !wasteCategory.isBlank()) {
            materialMultiplier = impactFactorRepository.findByCategoryIgnoreCase(wasteCategory)
                    .map(ImpactFactor::getMultiplier)
                    .orElse(1.0);
        }

        return materialAmount * factor * materialMultiplier;
    }
}
